version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
      - 80:80
    environment:
      INFLUX_DB_HOST: influxdb
    env_file:
      - .env.test
    restart: unless-stopped